# Tool name, which can differ from the repo name
name: Peasant

# Maintainer's name and email
maintainer:
  name: Justin Angel
  email: justin@blackhillsinfosec.com

# TTP tags with the format: <MITRE Tactic>/<Technique>
# URL for reference: https://attack.mitre.org/tactics/enterprise/
ttps:
  - reconnaissance/gahter_victim_identitiy_information
  
# Bulleted high level description. Please keep bullets brief.
descriptions:
  - Pull profile information from LinkedIn.
  
# Determines if the tool can be discussed publicly
# Valid Values: true, false
public: true
